# Configuration fragment for anchoring of a wrist rest to the main body,
# demonstrating the use of multiple mounts with a consistent angle to allow
# the position of the wrist rest to be adjusted.

wrist-rest:
  include: true
  style: threaded
  mounts:
  - fasteners:
      bolt-properties:
        m-diameter: 4
        head-type: socket
        total-length: 60
      height:
        first: 3
    angle: -1.2
    blocks:
      distance: 37
      width: 10
      main-side:
        position:
          anchor: t4
          side: NNE
          offset: [5, 8.5]
        depth: 10
      plinth-side:
        depth: 7
        pocket-height: -100
      aliases:
        wr0c: main-side
        wr0p: plinth-side
  - fasteners:
      bolt-properties:
        m-diameter: 4
        head-type: socket
        total-length: 45
      height:
        first: 3
    angle: -1.2
    blocks:
      distance: 30
      width: 10
      main-side:
        position:
          anchor: near-right
          side: SSW
          offset: [-5, 0]
        depth: 7
      plinth-side:
        depth: 7
        pocket-height: -100
      aliases:
        wr1c: main-side
        wr1p: plinth-side
