# WIP.

reflect: true
key-clusters:
  main:
    position:
      anchor: central-wip-3
      offset: [50, 0, -19.5]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
case:
  central-housing:
    include: true
    shape:
      width: 100
      edge:
        - offset: [0, -20, -5]
          alias: central-wip-1
        - offset: [0, -20, 30]
          alias: central-wip-2
        - offset: [0, -15, 35]
          alias: central-wip-3
        - offset: [0, 20, 35]
          alias: central-wip-4
        - offset: [0, 20, -5]
          alias: central-wip-5
