# Sandbox version. Work in progress.
# Configuration fragment for the base of a Concertina.
# This resembles the DMOTE but the hands are vertically oriented,
# and for this reason, the keyboard is joined by a central housing
# rather than fully split.

reflect: true
key-clusters:
  main:
    position:
      anchor: central-wip-3
      offset: [50, 0, -19.5]
    matrix-columns:
      - rows-above-home: 1
        rows-below-home: 1
      - rows-above-home: 1
    aliases:
      key-wip-1: [first, -1]
      key-wip-2: [first, 0]
      key-wip-3: [first, 1]
by-key:
  parameters:
    wall:
      west:
        extent: 1
        parallel: 5
        perpendicular: -10
case:
  central-housing:
    include: true
    shape:
      width: 100
      interface:
        - base:
            offset: [0, -20, -5]
            alias: central-wip-1
          adapter:
            offset: [0, 0, 0]
            alias: central-adapter-wip-1
        - base:
            offset: [0, -20, 30]
            alias: central-wip-2
          adapter:
            offset: [10, 0, 0]
            alias: central-adapter-wip-2
        - base:
            offset: [0, -15, 35]
            alias: central-wip-3
          adapter:
            offset: [10, 0, 0]
            alias: central-adapter-wip-3
        - base:
            offset: [0, 20, 35]
            alias: central-wip-4
          adapter:
            alias: central-adapter-wip-4
        - base:
            offset: [0, 25, 30]
            alias: central-wip-5
          adapter:
            alias: central-adapter-wip-5
        - base:
            offset: [0, 25, -5]
            alias: central-wip-6
          adapter:
            alias: central-adapter-wip-6
    adapter:
      include: true
      width: 10
      lip:
        include: true
        width:
          outer: 3
          taper: 2
      fasteners:
        diameter: 4
        length: 8
        positions:
          - starting-point: central-wip-2
            lateral-offset: 5
            radial-offset: 2
          - starting-point: central-wip-3
            lateral-offset: -5
            radial-offset: 10
      receivers:
        thickness:
          rim: 1.5
          bridge: 3
        width:
          inner: 4
          taper: 5
  bottom-plate:
    include: true
    thickness: 2
  tweaks:
    bridge-wip:
      - chunk-size: 3
        hull-around:
          - [key-wip-1, WSW, 0, 4]
          - [central-adapter-wip-1]
          - [key-wip-1, WSW, 1]
          - [central-adapter-wip-2]
          - [key-wip-2, WSW, 1]
          - [central-adapter-wip-3]
          - [key-wip-3, WNW, 1]
          - [central-adapter-wip-4]
          - [key-wip-3, WNW, 4]
          - [central-adapter-wip-6]
    mcu-holder-wip:
      - hull-around:
          - [mcu-plate, SE, 0, 2]
          - [mcu-plate, SW, 0, 2]
          - [sec-wip-2]
          - [sec-wip-1]
mcu:
  include: true
  position:
    anchor: central-wip-6
    corner: NNE
    offset: [0, -2, 0]
  support:
    lock:
      include: true
      plate:
        alias: mcu-plate
secondaries:
  sec-wip-1:
    anchor: central-wip-1
    offset: [-6, 2, 12.5]
  sec-wip-2:
    anchor: sec-wip-1
    offset: [7, 0, 0]
