# WIP.

reflect: true
key-clusters:
  main:
    position:
      anchor: central-wip-3
      offset: [50, 0, -19.5]
    matrix-columns:
      - rows-above-home: 1
        rows-below-home: 1
      - rows-above-home: 1
    aliases:
      key-wip-1: [first, -1]
      key-wip-2: [first, 0]
      key-wip-3: [first, 1]
by-key:
  parameters:
    wall:
      west:
        extent: 1
        parallel: 5
        perpendicular: -10
case:
  central-housing:
    include: true
    preview: true
    adapter:
      include: true
      width: 10
    shape:
      width: 100
      interface:
        - base:
            offset: [0, -20, -5]
            alias: central-wip-1
          adapter:
            offset: [0, 0, 0]
            alias: central-adapter-wip-1
        - base:
            offset: [0, -20, 30]
            alias: central-wip-2
          adapter:
            offset: [10, 0, 0]
            alias: central-adapter-wip-2
        - base:
            offset: [0, -15, 35]
            alias: central-wip-3
          adapter:
            offset: [10, 0, 0]
            alias: central-adapter-wip-3
        - base:
            offset: [0, 20, 35]
            alias: central-wip-4
          adapter:
            alias: central-adapter-wip-4
        - base:
            offset: [0, 20, -5]
            alias: central-wip-5
          adapter:
            alias: central-adapter-wip-5
  tweaks:
    bridge-wip:
      - chunk-size: 3
        hull-around:
          - [key-wip-1, WSW, 0, 4]
          - [central-adapter-wip-1]
          - [key-wip-1, WSW, 1]
          - [central-adapter-wip-2]
          - [key-wip-2, WSW, 1]
          - [central-adapter-wip-3]
          - [key-wip-3, WNW, 1]
          - [central-adapter-wip-4]
          - [key-wip-3, WNW, 4]
          - [central-adapter-wip-5]
    grip-wip:
      - chunk-size: 3
        hull-around:
          - [grip-wip-east]
          - [central-wip-2]
          - [grip-wip-west]
          - [central-wip-3]
mcu:
  include: true
  preview: true
  position:
    anchor: central-wip-5
    corner: NNE
    offset: [0, -2, 0]
  support:
    grip:
      anchors:
        - alias: grip-wip-east
          corner: SSE
          offset: [-1, 0]
        - alias: grip-wip-west
          corner: SSW
          offset: [1, 0]
