# A configuration fragment for a simple 12-key macropad.
# This might also serve as the core of a numpad and is easily extended.

key-clusters:
  main:
    anchoring:
      anchor: origin
      offset: [0, 0, 4.5]
    matrix-columns:
    - rows-above-home: 3
    - rows-above-home: 3
    - rows-above-home: 3
    aliases:
      back: [1, last]
      lower-left: [first, first]
      upper-left: [first, last]
      lower-right: [last, first]
      mid-right: [last, 2]
      upper-right: [last, last]
by-key:
  parameters:
    layout:
      pitch:
        intrinsic: -0.1
        base: 0.3
    wall:
      bevel: 1
      north:
        parallel: 10
        perpendicular: -2
      east:
        parallel: 8
        perpendicular: -16
      south:
        parallel: 8
        perpendicular: -16
      west:
        parallel: 8
        perpendicular: -16
  clusters:
    main:
      columns:
        last:
          rows:
            last:
              parameters:
                wall:
                  east:
                    extent: 1
main-body:
  key-mount-corner-margin: 2
  key-mount-thickness: 2
  web-thickness: 2
secondaries:
  back-wall:
    anchoring:
      anchor: upper-right
      side: NNE
      segment: 3
    translation: [0, 0, -10]
mcu:
  include: true
  intrinsic-rotation: [0, π/2, π/-2]  # Stand on the long edge.
  anchoring:
    anchor: back-wall
    offset: [0, -3.5, 0]
  support:
    lock:
      include: true
tweaks:
  flat-wall:
  - chunk-size: 2
    hull-around:
    - [mid-right, ENE, 2]
    - [upper-right, ESE, 1, 2]
    - [upper-right, ENE, 1]
    - [upper-right, NNE, 1, 3]
  - chunk-size: 2
    at-ground: true
    hull-around:
    - [mid-right, ENE, 3]
    - [upper-right, ESE, 2]
    - [upper-right, ENE, 1]
    - [upper-right, NNE, 3]
