# Configuration fragment for flattening each key cluster.
# As written, this will only be effective where no more specific corresponding
# settings are made, which is improbable.

by-key:
  parameters:
    layout:
      matrix:
        separation:
          row: 0
          column: 0
      pitch:
        progressive: 0
      roll:
        progressive: 0
