# Configuration fragment for visualization of an assembled keyboard.
# You probably don’t want to print with these settings.

keys:
  preview: true
main-body:
  bottom-plate:
    preview: true
central-housing:
  preview: true
mcu:
  preview: true
  support:
    preview: true
wrist-rest:
  preview: true
