# Configuration fragment for visualization of an assembled keyboard.
# You probably don’t want to print with these settings.

keys:
  preview: true
case:
  central-housing:
    preview: true
  bottom-plate:
    preview: true
mcu:
  preview: true
  support:
    preview: true
wrist-rest:
  preview: true
