# Configuration fragment for MX-style switches only.
#
# This illustrates the need to override the default style as well as those
# non-default styles that are defined in dmote/base.yaml.
#
# Skirt lengths are added to prevent collisions. This is needed because
# MX-style switches have a deeper base than ALPS-style switches, bringer the
# outer edges of long skirts into contact.

keys:
  styles:
    default:
      switch-type: mx
    minimal-short:
      switch-type: mx
      skirt-length: 3.5
    minimal-tall:
      switch-type: mx
      skirt-length: 3.5
