# A configuration fragment for Tom Short’s Dactyl-ManuForm, ca. v0.4.

# The long-term goal with this file is to have it produce Short’s design
# through the DMOTE application for upstream compatibility.

# As of DMOTE v0.6.0-SNAPSHOT, that is not yet possible, because:
# - No internal shelf for the MCU.
# - No USB A.
# - No wire hooks.

reflect: true
keys:
  styles:
    default:  # Rough approximation of SA family.
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 12.7, 6]
      unit-size: [1, 1]
    big:
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 20, 6]
      unit-size: [1, 1.5]
key-clusters:
  main:
    position:
      anchor: origin
      # To match upstream STL more exactly, raise by the thickness of the
      # bottom plate. The Dactyl-ManuForm was not raised above the ground
      # plane to compensate for a bottom plate, but the DMOTE is.
      offset: [1, 0, 12.9]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 1
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      mcu-base-key: [0, 0]
      back0: [0, last]
      back1: [1, last]
      back2: [2, last]
      right0: [last, 0]
  thumb0:
    position:
      anchor: m00
      offset: [-2, -28, -6]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    aliases:
      thumb-tr: [1, 0]  # Top right.
      thumb-tl: [0, 0]
  thumb1:
    position:
      anchor: thumb-tl
      offset: [3.5, -26, -15]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
    aliases:
      thumb-mr: [1, 0]
      thumb-ml: [1, 1]
      thumb-br: [0, 0]
      thumb-bl: [0, 1]
by-key:
  parameters:
    layout:
      matrix:
        separation:
          column: 1.5
          row: 1.2
    wall:
      thickness: 2
      north:
        parallel: 5
        perpendicular: -15
      east:
        parallel: 5
        perpendicular: -15
      south:
        parallel: 5
        perpendicular: -15
      west:
        parallel: 5
        perpendicular: -15
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 3
          pitch:
            base: 0
            progressive: 0.25
          roll:
            base: 0.26
            progressive: 0.09
      columns:
        first:
          parameters:
            wall:
              south:
                extent: 0
              west:
                parallel: 8
                perpendicular: -9
        "1":
          parameters:
            wall:
              south:
                extent: 0
        "2":
          parameters:
            layout:
              translation:
                mid: [0, 2.82, -4.5]
            wall:
              west:
                extent: 0
              south:
                extent: 0
        "4":
          parameters:
            layout:
              translation:
                late: [1, -12, 5.64]
    thumb0:
      parameters:
        key-style: big
        layout:
          pitch:
            base: 0.1745
          roll:
            base: -0.4014
          yaw:
            base: 0.1745
        wall:
          north:
            extent: 0
          east:
            extent: 0
          south:
            extent: 0
          west:
            extent: 0
      columns:
        first:
          parameters:
            layout:
              roll:
                intrinsic: 0
              yaw:
                intrinsic: 0
        last:
          parameters:
            layout:
              translation:
                late: [3, -4, -2.2]
    thumb1:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 1
          pitch:
            base: -0.02
          roll:
            base: -0.59
          yaw:
            base: 0.94
        wall:
          east:
            extent: 0
      columns:
        first:
          parameters:
            # Because of the long walls of the case, full-extent walls cause
            # problems with OpenSCAD’s projections to the ground plane.
            # Therefore, walls on the first column are restricted.
            wall:
              north:
                extent: 4
              south:
                extent: 4
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.26
                  translation:
                    early: [0, -1, 1.7]
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.05
                  translation:
                    early: [0, 1, 5.2]
        last:
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  yaw:
                    intrinsic: -0.06
                  translation:
                    early: [1.5, 0, 2.7]
            last:
              parameters:
                layout:
                  yaw:
                    intrinsic: -0.2
                  translation:
                    early: [0.6, 8, 4.5]
case:
  key-mount-thickness: 4
  key-mount-corner-margin: 1.5
  web-thickness: 3.5
  bottom-plate:
    include: true
    installation:
      thickness: 1.2
      inserts:
        include: true
        diameter:
          top: 5.1
          bottom: 5.31
        length: 3.8
      fasteners:
        bolt-properties:
          m-diameter: 3  # Speculation; Dactyl-ManuForm may have used non-metric.
          head-type: countersunk
          total-length: 6
        positions:
        - anchor: m00
          corner: WSW
          offset: [-3, -7]
        - anchor: back0
          corner: WSW
          offset: [0, 6]
        - anchor: back2
          corner: NNE
          offset: [13.5, -3]
        - anchor: m02
          corner: SSE
          offset: [-6, -4]
        - anchor: right0
          corner: ESE
          offset: [-1, 10]
  tweaks:
    webbing:
      - chunk-size: 3
        hull-around:  # Between the two thumb clusters.
        - [thumb-tl, WNW]
        - [thumb-ml, ENE]
        - [thumb-tl, WSW]
        - [thumb-ml, ESE]
        - [thumb-tl, SSE]
        - [thumb-mr, ENE]
        - [thumb-tr, SSW]
        - [thumb-mr, SSE]
        - [thumb-tr, SSE]
      - chunk-size: 3
        hull-around:  # Between thumb0 and the main cluster.
        - [thumb-tl, NNW]
        - [m00, SSW]
        - [thumb-tl, NNE]
        - [m00, SSE]
        - [thumb-tr, NNW]
        - [m01, SSW]
        - [thumb-tr, NNE]
        - hull-around:
          - [m01, SSE]
          - [m02, WNW]
        - [thumb-tr, ENE]
        - hull-around:
          - [m02, WNW]
          - [m02, WSW]
        - [thumb-tr, ESE]
        - [m02, SSW]
        - hull-around:
          - [m02, SSE]
          - [m03, WSW]
    to-floor:
      - at-ground: true
        hull-around:
        - [m00, WSW, 3, 4]
        - [thumb-ml, NNE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-ml, NNW, 3, 4]
        - [thumb-bl, NNE, 3, 4]
      - at-ground: true
        hull-around:
        - [m03, SSW, 3, 4]
        - [thumb-tr, SSE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-tr, SSE, 3, 4]
        - [thumb-mr, SSE, 3, 4]
      - at-ground: true
        hull-around:
        - [thumb-mr, SSW, 3, 4]
        - [thumb-br, SSE, 3, 4]
      - at-ground: true
        above-ground: false  # Extend the bottom plate only.
        hull-around:
        - [m03, SSW, 3]
        - [thumb-tr, SSE, 3]
        - [thumb-ml, NNE, 3]
        - [m00, WSW, 3]
      - at-ground: true
        above-ground: false  # Extend the bottom plate only.
        hull-around:
        - [thumb-mr, SSE, 3]
        - [thumb-ml, NNE, 3]
        - [thumb-tr, SSE, 3]
    thumb-to-finger-gap:
      - chunk-size: 3
        hull-around:
        - [m00, WSW, 0, 2]
        - [m00, WSW, 3, 4]
        - [thumb-tl, WNW]
        - [thumb-ml, NNE, 0, 4]
      - chunk-size: 2
        hull-around:
        - [thumb-mr, SSE, 0, 4]
        - [thumb-tr, SSE, 0, 4]
        - [m03, SSW, 0, 4]
    # MCU-related tweaks correspond to nothing in the upstream.
    # They should be moved into a variant YAML file when Short’s
    # MCU shelf is supported by the DMOTE application.
    mcu-grip:
      - chunk-size: 2
        hull-around:
        - [grip-west-corner-forward]
        - [grip-west-corner-backward]
        - [grip-west-center-outermost]
      - chunk-size: 2
        hull-around:
        - [grip-east-corner-forward]
        - [grip-east-corner-backward]
        - [grip-east-center-outermost]
      - hull-around:
        - [grip-west-center-outermost]
        - [grip-west-center-innermost]
        - [grip-east-center-innermost]
        - [grip-east-center-outermost]
    grip-to-web:
      - hull-around:
        - [grip-west-center-outermost]
        - [grip-east-center-outermost]
        - [grip-rear-west]
        - [grip-rear-east]
      - hull-around:
        - [grip-rear-west]
        - [grip-rear-east]
        - [back0, ESE, 0]
        - [mcu-base-key, ENE, 0]
mcu:
  include: true
  type: promicro
  position:
    anchor: back0
    corner: NNE
    offset: [4, 0, -6]
  support:
    # There is none of the
    grip:
      size: [2, 2, 5]
      anchors:
        # One group of anchors goes round the south-west corner.
        - alias: grip-west-corner-forward
          corner: SW
          offset: [-1, -0.5]
        - alias: grip-west-corner-backward
          corner: SW
          offset: [-1, -1]
        - alias: grip-west-center-outermost
          corner: SW
          offset: [4, -1]
        - alias: grip-west-center-innermost
          corner: SW
          offset: [8, 0.5]
        # A corresponding group goes round the south-east corner.
        - alias: grip-east-corner-forward
          corner: SE
          offset: [1, -0.5]
        - alias: grip-east-corner-backward
          corner: SE
          offset: [1, -1]
        - alias: grip-east-center-outermost
          corner: SE
          offset: [-4, -1]
        - alias: grip-east-center-innermost
          corner: SE
          offset: [-8, 0.5]
        # A pair of anchors above and further behind the PCB.
        # These serve as a bridge to the key webbing.
        - alias: grip-rear-west
          corner: SW
          offset: [10, -5, 5]
        - alias: grip-rear-east
          corner: SE
          offset: [-10, -5, 5]
connection:
  include: true
  socket-size: [10.78, 9, 18.38]
  position:
    anchor: back0
    corner: NNE
    offset: [-9, 1.3, 1]
